openapi: 3.0.0
info:
  title: Profile Service
  version: 0.0.1
  description: Manages profiles.
paths:
  /rpc/Profile.CreateProfile:
    post:
      operationId: createProfile
      summary: Creates a profile
      description: Stores a new profile.
      requestBody:
        content:
          application/json:
            schema:
              $ref: models.yaml#/components/schemas/createProfileParams
      responses:
        '200':
          description: |-
            ## Error Cases

            | Code | Message | Description |
            | - | - | - |
            | -32700 | parse error | Invalid JSON was received by the server. |
            | -32603 | internal error | Internal JSON-RPC error. |
            | -32602 | invalid params | Invalid method parameter(s). |
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/createProfileResp
  /rpc/Profile.GetProfile:
    post:
      operationId: getProfile
      summary: Gets a profile
      description: Retrieves an existing profile.
      requestBody:
        content:
          application/json:
            schema:
              $ref: models.yaml#/components/schemas/getProfileParams
      responses:
        '200':
          description: |-
            ## Error Cases

            | Code | Message | Description |
            | - | - | - |
            | -32700 | parse error | Invalid JSON was received by the server. |
            | -32603 | internal error | Internal JSON-RPC error. |
            | -32602 | invalid params | Invalid method parameter(s). |
            | 1 | profile not found | The profile operated does not exist. |
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/getProfileResp
  /rpc/Profile.UpdateProfile:
    post:
      operationId: updateProfile
      summary: Updates a profile
      description: Modifies an existing profile.
      requestBody:
        content:
          application/json:
            schema:
              $ref: models.yaml#/components/schemas/updateProfileParams
      responses:
        '200':
          description: |-
            ## Error Cases

            | Code | Message | Description |
            | - | - | - |
            | -32700 | parse error | Invalid JSON was received by the server. |
            | -32603 | internal error | Internal JSON-RPC error. |
            | -32602 | invalid params | Invalid method parameter(s). |
            | 1 | profile not found | The profile operated does not exist. |
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/updateProfileResp
  /rpc/Profile.DeleteProfile:
    post:
      operationId: deleteProfile
      summary: Deletes a profile
      description: Purges an existing profile.
      requestBody:
        content:
          application/json:
            schema:
              $ref: models.yaml#/components/schemas/deleteProfileParams
      responses:
        '200':
          description: |-
            ## Error Cases

            | Code | Message | Description |
            | - | - | - |
            | -32700 | parse error | Invalid JSON was received by the server. |
            | -32603 | internal error | Internal JSON-RPC error. |
            | -32602 | invalid params | Invalid method parameter(s). |
            | 1 | profile not found | The profile operated does not exist. |
          content:
            application/json:
              schema:
                $ref: models.yaml#/components/schemas/deleteProfileResp
