// Code generated by jrohc. DO NOT EDIT.

package userapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

const ErrorProfileNotFound apicommon.ErrorCode = 1

func NewProfileNotFoundError() *apicommon.Error {
	return &apicommon.Error{
		Code:    ErrorProfileNotFound,
		Message: "profile not found",
	}
}

var errProfileNotFound *apicommon.Error = NewProfileNotFoundError()
var ErrProfileNotFound error = errProfileNotFound
