// Code generated by jrohc. DO NOT EDIT.

package userapi

import (
	apicommon "example/api/apicommon"
)

const ErrorProfileNotFound apicommon.ErrorCode = 1

var ErrProfileNotFound = &apicommon.Error{
	Code:    ErrorProfileNotFound,
	Message: "profile not found",
}
