// Code generated by jrohc. DO NOT EDIT.

package userapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

const (
	ProfileBulkService_CreateProfilesInBulk apicommon.MethodIndex = iota
	ProfileBulkService_GetProfilesInBulk
	ProfileBulkService_UpdateProfilesInBulk
	ProfileBulkService_DeleteProfilesInBulk
)

const (
	ProfileService_CreateProfile apicommon.MethodIndex = iota
	ProfileService_GetProfile
	ProfileService_UpdateProfile
	ProfileService_DeleteProfile
)
