// Code generated by jrohc. DO NOT EDIT.

package userapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

type CreateProfileParams struct {
	Profile Profile `json:"profile"`
}

type CreateProfileResp struct {
	TraceID string                `json:"traceID"`
	Error   *apicommon.Error      `json:"error,omitempty"`
	Results *CreateProfileResults `json:"results,omitempty"`
}

type CreateProfileResults struct {
	ProfileID int64 `json:"profileID"`
}

type GetProfileParams struct {
	ProfileID int64 `json:"profileID"`
}

type GetProfileResp struct {
	TraceID string             `json:"traceID"`
	Error   *apicommon.Error   `json:"error,omitempty"`
	Results *GetProfileResults `json:"results,omitempty"`
}

type GetProfileResults struct {
	Profile Profile `json:"profile"`
}

type UpdateProfileParams struct {
	ProfilePatch ProfilePatch `json:"profilePatch"`
}

type UpdateProfileResp struct {
	TraceID string           `json:"traceID"`
	Error   *apicommon.Error `json:"error,omitempty"`
}

type DeleteProfileParams struct {
	ProfileID int64 `json:"profileID"`
}

type DeleteProfileResp struct {
	TraceID string           `json:"traceID"`
	Error   *apicommon.Error `json:"error,omitempty"`
}

type Profile struct {
	ID         int64      `json:"id"`
	Nickname   string     `json:"nickname"`
	GenderType GenderType `json:"genderType"`
	Weight     *float64   `json:"weight,omitempty"`
	Height     *int32     `json:"height,omitempty"`
}

type GenderType int32

const (
	GenderFemale GenderType = 1
	GenderMale   GenderType = 2
	GenderOther  GenderType = 3
)

type ProfilePatch struct {
	ID         int64       `json:"id"`
	Nickname   *string     `json:"nickname,omitempty"`
	GenderType *GenderType `json:"genderType,omitempty"`
	Weight     *float64    `json:"weight,omitempty"`
	Height     *int32      `json:"height,omitempty"`
}
