// Code generated by jrohc. DO NOT EDIT.

package userapi

import (
	context "context"
	apicommon "github.com/go-tk/jroh/go/apicommon"
	http "net/http"
)

const (
	ProfileBulkService_CreateProfilesInBulk apicommon.MethodIndex = 0
	ProfileBulkService_GetProfilesInBulk    apicommon.MethodIndex = 1
	ProfileBulkService_UpdateProfilesInBulk apicommon.MethodIndex = 2
	ProfileBulkService_DeleteProfilesInBulk apicommon.MethodIndex = 3
)

type ProfileBulkService interface {
	CreateProfilesInBulk(ctx context.Context, params *CreateProfilesInBulkParams, results *CreateProfilesInBulkResults) (err error)
	GetProfilesInBulk(ctx context.Context, params *GetProfilesInBulkParams, results *GetProfilesInBulkResults) (err error)
	UpdateProfilesInBulk(ctx context.Context, params *UpdateProfilesInBulkParams, results *UpdateProfilesInBulkResults) (err error)
	DeleteProfilesInBulk(ctx context.Context, params *DeleteProfilesInBulkParams, results *DeleteProfilesInBulkResults) (err error)
}

type DummyProfileBulkService struct{}

var _ ProfileBulkService = DummyProfileBulkService{}

func (DummyProfileBulkService) CreateProfilesInBulk(context.Context, *CreateProfilesInBulkParams, *CreateProfilesInBulkResults) error {
	return nil
}
func (DummyProfileBulkService) GetProfilesInBulk(context.Context, *GetProfilesInBulkParams, *GetProfilesInBulkResults) error {
	return nil
}
func (DummyProfileBulkService) UpdateProfilesInBulk(context.Context, *UpdateProfilesInBulkParams, *UpdateProfilesInBulkResults) error {
	return nil
}
func (DummyProfileBulkService) DeleteProfilesInBulk(context.Context, *DeleteProfilesInBulkParams, *DeleteProfilesInBulkResults) error {
	return nil
}

func RegisterHandlersOfProfileBulkService(service ProfileBulkService, serveMux *http.ServeMux, options apicommon.RegisterHandlersOptions) {
	options.Normalize(4)
	{
		middlewares := options.Middlewares[ProfileBulkService_CreateProfilesInBulk]
		rpcInterceptors := options.RPCInterceptors[ProfileBulkService_CreateProfilesInBulk]
		incomingRPCFactory := func(traceID string) *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      CreateProfilesInBulkParams
				Results     CreateProfilesInBulkResults
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return service.CreateProfilesInBulk(ctx, rpc.Params().(*CreateProfilesInBulkParams), rpc.Results().(*CreateProfilesInBulkResults))
			}
			s.IncomingRPC.Init(
				"User",
				"ProfileBulk",
				"CreateProfilesInBulk",
				traceID,
				&s.Params,
				&s.Results,
				rpcHandler,
				rpcInterceptors,
			)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(middlewares, options.TraceIDGenerator, incomingRPCFactory)
		serveMux.Handle("/rpc/ProfileBulk.CreateProfilesInBulk", handler)
	}
	{
		middlewares := options.Middlewares[ProfileBulkService_GetProfilesInBulk]
		rpcInterceptors := options.RPCInterceptors[ProfileBulkService_GetProfilesInBulk]
		incomingRPCFactory := func(traceID string) *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      GetProfilesInBulkParams
				Results     GetProfilesInBulkResults
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return service.GetProfilesInBulk(ctx, rpc.Params().(*GetProfilesInBulkParams), rpc.Results().(*GetProfilesInBulkResults))
			}
			s.IncomingRPC.Init(
				"User",
				"ProfileBulk",
				"GetProfilesInBulk",
				traceID,
				&s.Params,
				&s.Results,
				rpcHandler,
				rpcInterceptors,
			)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(middlewares, options.TraceIDGenerator, incomingRPCFactory)
		serveMux.Handle("/rpc/ProfileBulk.GetProfilesInBulk", handler)
	}
	{
		middlewares := options.Middlewares[ProfileBulkService_UpdateProfilesInBulk]
		rpcInterceptors := options.RPCInterceptors[ProfileBulkService_UpdateProfilesInBulk]
		incomingRPCFactory := func(traceID string) *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      UpdateProfilesInBulkParams
				Results     UpdateProfilesInBulkResults
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return service.UpdateProfilesInBulk(ctx, rpc.Params().(*UpdateProfilesInBulkParams), rpc.Results().(*UpdateProfilesInBulkResults))
			}
			s.IncomingRPC.Init(
				"User",
				"ProfileBulk",
				"UpdateProfilesInBulk",
				traceID,
				&s.Params,
				&s.Results,
				rpcHandler,
				rpcInterceptors,
			)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(middlewares, options.TraceIDGenerator, incomingRPCFactory)
		serveMux.Handle("/rpc/ProfileBulk.UpdateProfilesInBulk", handler)
	}
	{
		middlewares := options.Middlewares[ProfileBulkService_DeleteProfilesInBulk]
		rpcInterceptors := options.RPCInterceptors[ProfileBulkService_DeleteProfilesInBulk]
		incomingRPCFactory := func(traceID string) *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      DeleteProfilesInBulkParams
				Results     DeleteProfilesInBulkResults
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return service.DeleteProfilesInBulk(ctx, rpc.Params().(*DeleteProfilesInBulkParams), rpc.Results().(*DeleteProfilesInBulkResults))
			}
			s.IncomingRPC.Init(
				"User",
				"ProfileBulk",
				"DeleteProfilesInBulk",
				traceID,
				&s.Params,
				&s.Results,
				rpcHandler,
				rpcInterceptors,
			)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(middlewares, options.TraceIDGenerator, incomingRPCFactory)
		serveMux.Handle("/rpc/ProfileBulk.DeleteProfilesInBulk", handler)
	}
}
