// Code generated by jrohc. DO NOT EDIT.

package fooapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

const (
	Test_DoSomething apicommon.MethodIndex = iota
	Test_DoSomething2
	Test_DoSomething3
)
