openapi: 3.0.0
info:
  title: Builtins
  version: ''
paths: {}
components:
  schemas:
    rpcError:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: A Number that indicates the error type that occurred.
          example: 10001
        message:
          type: string
          description: A String providing a short description of the error.
          example: something wrong
        data:
          type: object
          additionalProperties: true
          description: A Structured value that contains additional information about
            the error.
      required:
      - code
      - message
