// Code generated by jrohc. DO NOT EDIT.

package barapi

import (
	context "context"
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

type TestService interface {
	DoSomething(ctx context.Context, results *DoSomethingResults) (err error)
}

func RegisterTestService(service TestService, router *apicommon.Router, serverOptions apicommon.ServerOptions) {
	serverOptions.Sanitize()
	var serverMiddlewareTable [NumberOfTestMethods][]apicommon.ServerMiddleware
	apicommon.FillServerMiddlewareTable(serverMiddlewareTable[:], serverOptions.Middlewares)
	var rpcFiltersTable [NumberOfTestMethods][]apicommon.RPCHandler
	apicommon.FillRPCFiltersTable(rpcFiltersTable[:], serverOptions.RPCFilters)
	{
		serverMiddlewares := serverMiddlewareTable[Test_DoSomething]
		rpcFilters := rpcFiltersTable[Test_DoSomething]
		incomingRPCFactory := func() *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Results     DoSomethingResults
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return service.DoSomething(ctx, rpc.Results().(*DoSomethingResults))
			}
			s.IncomingRPC.Init("Bar", "Test", "DoSomething", "Bar.Test.DoSomething", Test_DoSomething, nil, &s.Results, rpcHandler, rpcFilters)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(serverMiddlewares, incomingRPCFactory, serverOptions.TraceIDGenerator)
		router.AddRoute("/rpc/Bar.Test.DoSomething", handler, "Bar.Test.DoSomething", serverMiddlewares, rpcFilters)
	}
}

type TestServiceFuncs struct {
	DoSomethingFunc func(context.Context, *DoSomethingResults) error
}

var _ TestService = (*TestServiceFuncs)(nil)

func (sf *TestServiceFuncs) DoSomething(ctx context.Context, results *DoSomethingResults) error {
	if f := sf.DoSomethingFunc; f != nil {
		return f(ctx, results)
	}
	return apicommon.ErrNotImplemented
}
