// Code generated by jrohc. DO NOT EDIT.

package barapi

import (
	context "context"
	apicommon "github.com/go-tk/jroh/go/apicommon"
	http "net/http"
)

type TestServer interface {
	DoSomething(ctx context.Context) (err error)
}

func RegisterTestServer(s TestServer, router *apicommon.Router, options apicommon.ServerOptions) {
	options.Sanitize()
	var rpcFiltersTable [NumberOfTestMethods][]apicommon.IncomingRPCHandler
	apicommon.FillIncomingRPCFiltersTable(rpcFiltersTable[:], options.RPCFilters)
	{
		rpcFilters := rpcFiltersTable[Test_DoSomething]
		handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			var a struct {
				rpc     apicommon.IncomingRPC
				params  apicommon.DummyModel
				results apicommon.DummyModel
			}
			a.rpc.Namespace = "Bar"
			a.rpc.ServiceName = "Test"
			a.rpc.MethodName = "DoSomething"
			a.rpc.FullMethodName = "Bar.Test.DoSomething"
			a.rpc.MethodIndex = Test_DoSomething
			a.rpc.Params = &a.params
			a.rpc.Results = &a.results
			a.rpc.SetHandler(func(ctx context.Context, rpc *apicommon.IncomingRPC) error {
				return s.DoSomething(ctx)
			})
			a.rpc.SetFilters(rpcFilters)
			apicommon.HandleRequest(r, &a.rpc, options.TraceIDGenerator, w)
		})
		router.AddRoute("/rpc/Bar.Test.DoSomething", handler, "Bar.Test.DoSomething", rpcFilters)
	}
}

type TestServerFuncs struct {
	DoSomethingFunc func(context.Context) error
}

var _ TestServer = (*TestServerFuncs)(nil)

func (sf *TestServerFuncs) DoSomething(ctx context.Context) error {
	if f := sf.DoSomethingFunc; f != nil {
		return f(ctx)
	}
	return apicommon.NewNotImplementedError()
}
