// Code generated by jrohc. DO NOT EDIT.

package petstoreapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

const ErrorPetAlreadyExists apicommon.ErrorCode = 2001

func NewPetAlreadyExistsError() *apicommon.Error {
	return &apicommon.Error{
		Code:    ErrorPetAlreadyExists,
		Message: "pet already exists",
	}
}

var errPetAlreadyExists *apicommon.Error = NewPetAlreadyExistsError()
var ErrPetAlreadyExists error = errPetAlreadyExists

const ErrorPetNotFound apicommon.ErrorCode = 2002

func NewPetNotFoundError() *apicommon.Error {
	return &apicommon.Error{
		Code:    ErrorPetNotFound,
		Message: "pet not found",
	}
}

var errPetNotFound *apicommon.Error = NewPetNotFoundError()
var ErrPetNotFound error = errPetNotFound

const ErrorUserAlreadyExists apicommon.ErrorCode = 1001

func NewUserAlreadyExistsError() *apicommon.Error {
	return &apicommon.Error{
		Code:    ErrorUserAlreadyExists,
		Message: "user already exists",
	}
}

var errUserAlreadyExists *apicommon.Error = NewUserAlreadyExistsError()
var ErrUserAlreadyExists error = errUserAlreadyExists

const ErrorUserNotFound apicommon.ErrorCode = 1002

func NewUserNotFoundError() *apicommon.Error {
	return &apicommon.Error{
		Code:    ErrorUserNotFound,
		Message: "user not found",
	}
}

var errUserNotFound *apicommon.Error = NewUserNotFoundError()
var ErrUserNotFound error = errUserNotFound
