// Code generated by jrohc. DO NOT EDIT.

package petstoreapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

const ErrorPetAlreadyExists apicommon.ErrorCode = 2001

func NewPetAlreadyExistsError() *apicommon.Error {
	return &apicommon.Error{
		Code:       ErrorPetAlreadyExists,
		StatusCode: 422,
		Message:    "pet already exists",
	}
}

const ErrorPetNotFound apicommon.ErrorCode = 2002

func NewPetNotFoundError() *apicommon.Error {
	return &apicommon.Error{
		Code:       ErrorPetNotFound,
		StatusCode: 422,
		Message:    "pet not found",
	}
}

const ErrorUserAlreadyExists apicommon.ErrorCode = 1001

func NewUserAlreadyExistsError() *apicommon.Error {
	return &apicommon.Error{
		Code:       ErrorUserAlreadyExists,
		StatusCode: 422,
		Message:    "user already exists",
	}
}

const ErrorUserNotFound apicommon.ErrorCode = 1002

func NewUserNotFoundError() *apicommon.Error {
	return &apicommon.Error{
		Code:       ErrorUserNotFound,
		StatusCode: 422,
		Message:    "user not found",
	}
}
