// Code generated by jrohc. DO NOT EDIT.

package petstoreapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

const (
	Pet_AddPet    apicommon.MethodIndex = 0
	Pet_GetPet    apicommon.MethodIndex = 1
	Pet_GetPets   apicommon.MethodIndex = 2
	Pet_UpdatePet apicommon.MethodIndex = 3
	Pet_FindPets  apicommon.MethodIndex = 4
)

const NumberOfPetMethods = 5

const (
	Store_CreateOrder apicommon.MethodIndex = 0
	Store_GetOrder    apicommon.MethodIndex = 1
)

const NumberOfStoreMethods = 2

const (
	User_CreateUser apicommon.MethodIndex = 0
	User_GetUser    apicommon.MethodIndex = 1
	User_GetUsers   apicommon.MethodIndex = 2
	User_UpdateUser apicommon.MethodIndex = 3
)

const NumberOfUserMethods = 4
