// Code generated by jrohc. DO NOT EDIT.

package petstoreapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

const (
	Pet_AddPet apicommon.MethodIndex = iota
	Pet_GetPet
	Pet_GetPets
	Pet_UpdatePet
	Pet_FindPets
)

const (
	Store_CreateOrder apicommon.MethodIndex = iota
	Store_GetOrder
)

const (
	User_CreateUser apicommon.MethodIndex = iota
	User_GetUser
	User_GetUsers
	User_UpdateUser
)
