// Code generated by jrohc. DO NOT EDIT.

package petstoreapi

const (
	Pet_AddPet    = 0
	Pet_GetPet    = 1
	Pet_GetPets   = 2
	Pet_UpdatePet = 3
	Pet_FindPets  = 4
)

const NumberOfPetMethods = 5

const (
	Store_CreateOrder = 0
	Store_GetOrder    = 1
)

const NumberOfStoreMethods = 2

const (
	User_CreateUser = 0
	User_GetUser    = 1
	User_GetUsers   = 2
	User_UpdateUser = 3
)

const NumberOfUserMethods = 4
