// Code generated by jrohc. DO NOT EDIT.

package petstoreapi

import (
	context "context"
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

type PetService interface {
	AddPet(ctx context.Context, params *AddPetParams) (err error)
	GetPet(ctx context.Context, params *GetPetParams, results *GetPetResults) (err error)
	GetPets(ctx context.Context, params *GetPetsParams, results *GetPetsResults) (err error)
	UpdatePet(ctx context.Context, params *UpdatePetParams) (err error)
	FindPets(ctx context.Context, params *FindPetsParams, results *FindPetsResults) (err error)
}

func RegisterPetService(service PetService, router *apicommon.Router, serverOptions apicommon.ServerOptions) {
	serverOptions.Sanitize()
	var serverMiddlewareTable [NumberOfPetMethods][]apicommon.ServerMiddleware
	apicommon.FillServerMiddlewareTable(serverMiddlewareTable[:], serverOptions.Middlewares)
	var rpcFiltersTable [NumberOfPetMethods][]apicommon.RPCHandler
	apicommon.FillRPCFiltersTable(rpcFiltersTable[:], serverOptions.RPCFilters)
	{
		serverMiddlewares := serverMiddlewareTable[Pet_AddPet]
		rpcFilters := rpcFiltersTable[Pet_AddPet]
		incomingRPCFactory := func() *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      AddPetParams
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return service.AddPet(ctx, rpc.Params().(*AddPetParams))
			}
			s.IncomingRPC.Init("Petstore", "Pet", "AddPet", "Petstore.Pet.AddPet", Pet_AddPet, &s.Params, nil, rpcHandler, rpcFilters)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(serverMiddlewares, incomingRPCFactory, serverOptions.TraceIDGenerator)
		router.AddRoute("/rpc/Petstore.Pet.AddPet", handler, "Petstore.Pet.AddPet", serverMiddlewares, rpcFilters)
	}
	{
		serverMiddlewares := serverMiddlewareTable[Pet_GetPet]
		rpcFilters := rpcFiltersTable[Pet_GetPet]
		incomingRPCFactory := func() *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      GetPetParams
				Results     GetPetResults
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return service.GetPet(ctx, rpc.Params().(*GetPetParams), rpc.Results().(*GetPetResults))
			}
			s.IncomingRPC.Init("Petstore", "Pet", "GetPet", "Petstore.Pet.GetPet", Pet_GetPet, &s.Params, &s.Results, rpcHandler, rpcFilters)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(serverMiddlewares, incomingRPCFactory, serverOptions.TraceIDGenerator)
		router.AddRoute("/rpc/Petstore.Pet.GetPet", handler, "Petstore.Pet.GetPet", serverMiddlewares, rpcFilters)
	}
	{
		serverMiddlewares := serverMiddlewareTable[Pet_GetPets]
		rpcFilters := rpcFiltersTable[Pet_GetPets]
		incomingRPCFactory := func() *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      GetPetsParams
				Results     GetPetsResults
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return service.GetPets(ctx, rpc.Params().(*GetPetsParams), rpc.Results().(*GetPetsResults))
			}
			s.IncomingRPC.Init("Petstore", "Pet", "GetPets", "Petstore.Pet.GetPets", Pet_GetPets, &s.Params, &s.Results, rpcHandler, rpcFilters)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(serverMiddlewares, incomingRPCFactory, serverOptions.TraceIDGenerator)
		router.AddRoute("/rpc/Petstore.Pet.GetPets", handler, "Petstore.Pet.GetPets", serverMiddlewares, rpcFilters)
	}
	{
		serverMiddlewares := serverMiddlewareTable[Pet_UpdatePet]
		rpcFilters := rpcFiltersTable[Pet_UpdatePet]
		incomingRPCFactory := func() *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      UpdatePetParams
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return service.UpdatePet(ctx, rpc.Params().(*UpdatePetParams))
			}
			s.IncomingRPC.Init("Petstore", "Pet", "UpdatePet", "Petstore.Pet.UpdatePet", Pet_UpdatePet, &s.Params, nil, rpcHandler, rpcFilters)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(serverMiddlewares, incomingRPCFactory, serverOptions.TraceIDGenerator)
		router.AddRoute("/rpc/Petstore.Pet.UpdatePet", handler, "Petstore.Pet.UpdatePet", serverMiddlewares, rpcFilters)
	}
	{
		serverMiddlewares := serverMiddlewareTable[Pet_FindPets]
		rpcFilters := rpcFiltersTable[Pet_FindPets]
		incomingRPCFactory := func() *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      FindPetsParams
				Results     FindPetsResults
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return service.FindPets(ctx, rpc.Params().(*FindPetsParams), rpc.Results().(*FindPetsResults))
			}
			s.IncomingRPC.Init("Petstore", "Pet", "FindPets", "Petstore.Pet.FindPets", Pet_FindPets, &s.Params, &s.Results, rpcHandler, rpcFilters)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(serverMiddlewares, incomingRPCFactory, serverOptions.TraceIDGenerator)
		router.AddRoute("/rpc/Petstore.Pet.FindPets", handler, "Petstore.Pet.FindPets", serverMiddlewares, rpcFilters)
	}
}

type PetServiceFuncs struct {
	AddPetFunc    func(context.Context, *AddPetParams) error
	GetPetFunc    func(context.Context, *GetPetParams, *GetPetResults) error
	GetPetsFunc   func(context.Context, *GetPetsParams, *GetPetsResults) error
	UpdatePetFunc func(context.Context, *UpdatePetParams) error
	FindPetsFunc  func(context.Context, *FindPetsParams, *FindPetsResults) error
}

var _ PetService = (*PetServiceFuncs)(nil)

func (sf *PetServiceFuncs) AddPet(ctx context.Context, params *AddPetParams) error {
	if f := sf.AddPetFunc; f != nil {
		return f(ctx, params)
	}
	return apicommon.ErrNotImplemented
}

func (sf *PetServiceFuncs) GetPet(ctx context.Context, params *GetPetParams, results *GetPetResults) error {
	if f := sf.GetPetFunc; f != nil {
		return f(ctx, params, results)
	}
	return apicommon.ErrNotImplemented
}

func (sf *PetServiceFuncs) GetPets(ctx context.Context, params *GetPetsParams, results *GetPetsResults) error {
	if f := sf.GetPetsFunc; f != nil {
		return f(ctx, params, results)
	}
	return apicommon.ErrNotImplemented
}

func (sf *PetServiceFuncs) UpdatePet(ctx context.Context, params *UpdatePetParams) error {
	if f := sf.UpdatePetFunc; f != nil {
		return f(ctx, params)
	}
	return apicommon.ErrNotImplemented
}

func (sf *PetServiceFuncs) FindPets(ctx context.Context, params *FindPetsParams, results *FindPetsResults) error {
	if f := sf.FindPetsFunc; f != nil {
		return f(ctx, params, results)
	}
	return apicommon.ErrNotImplemented
}
