// Code generated by jrohc. DO NOT EDIT.

package petstoreapi

import (
	context "context"
	fmt "fmt"
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

type StoreClient interface {
	CreateOrder(ctx context.Context, params *CreateOrderParams) (results *CreateOrderResults, err error)
	GetOrder(ctx context.Context, params *GetOrderParams) (results *GetOrderResults, err error)
}

type storeClient struct {
	rpcBaseURL      string
	options         apicommon.ClientOptions
	rpcFiltersTable [NumberOfStoreMethods][]apicommon.OutgoingRPCHandler
}

func NewStoreClient(rpcBaseURL string, options apicommon.ClientOptions) StoreClient {
	var c storeClient
	c.rpcBaseURL = rpcBaseURL
	c.options = options
	c.options.Sanitize()
	apicommon.FillOutgoingRPCFiltersTable(c.rpcFiltersTable[:], options.RPCFilters)
	return &c
}

func (c *storeClient) CreateOrder(ctx context.Context, params *CreateOrderParams) (*CreateOrderResults, error) {
	var a struct {
		rpc     apicommon.OutgoingRPC
		params  CreateOrderParams
		results CreateOrderResults
	}
	a.rpc.Namespace = "Petstore"
	a.rpc.ServiceName = "Store"
	a.rpc.MethodName = "CreateOrder"
	a.rpc.FullMethodName = "Petstore.Store.CreateOrder"
	a.rpc.MethodIndex = Store_CreateOrder
	a.params = *params
	a.rpc.Params = &a.params
	a.rpc.Results = &a.results
	if err := c.doRPC(ctx, &a.rpc, "/rpc/Petstore.Store.CreateOrder"); err != nil {
		return nil, err
	}
	return &a.results, nil
}

func (c *storeClient) GetOrder(ctx context.Context, params *GetOrderParams) (*GetOrderResults, error) {
	var a struct {
		rpc     apicommon.OutgoingRPC
		params  GetOrderParams
		results GetOrderResults
	}
	a.rpc.Namespace = "Petstore"
	a.rpc.ServiceName = "Store"
	a.rpc.MethodName = "GetOrder"
	a.rpc.FullMethodName = "Petstore.Store.GetOrder"
	a.rpc.MethodIndex = Store_GetOrder
	a.params = *params
	a.rpc.Params = &a.params
	a.rpc.Results = &a.results
	if err := c.doRPC(ctx, &a.rpc, "/rpc/Petstore.Store.GetOrder"); err != nil {
		return nil, err
	}
	return &a.results, nil
}

func (c *storeClient) doRPC(ctx context.Context, rpc *apicommon.OutgoingRPC, rpcPath string) error {
	if timeout := c.options.Timeout; timeout >= 1 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, timeout)
		defer cancel()
	}
	rpc.Transport = c.options.Transport
	rpc.URL = c.rpcBaseURL + rpcPath
	rpc.SetHandler(apicommon.HandleOutgoingRPC)
	rpc.SetFilters(c.rpcFiltersTable[rpc.MethodIndex])
	if err := rpc.Do(ctx); err != nil {
		return fmt.Errorf("rpc failed; fullMethodName=%q traceID=%q: %w", rpc.FullMethodName, rpc.TraceID, err)
	}
	return nil
}

type StoreClientFuncs struct {
	CreateOrderFunc func(context.Context, *CreateOrderParams) (*CreateOrderResults, error)
	GetOrderFunc    func(context.Context, *GetOrderParams) (*GetOrderResults, error)
}

var _ StoreClient = (*StoreClientFuncs)(nil)

func (cf *StoreClientFuncs) CreateOrder(ctx context.Context, params *CreateOrderParams) (*CreateOrderResults, error) {
	if f := cf.CreateOrderFunc; f != nil {
		return f(ctx, params)
	}
	return nil, apicommon.NewNotImplementedError()
}

func (cf *StoreClientFuncs) GetOrder(ctx context.Context, params *GetOrderParams) (*GetOrderResults, error) {
	if f := cf.GetOrderFunc; f != nil {
		return f(ctx, params)
	}
	return nil, apicommon.NewNotImplementedError()
}
