// Code generated by jrohc. DO NOT EDIT.

package petstoreapi

import (
	context "context"
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

type StoreClient interface {
	CreateOrder(ctx context.Context, params *CreateOrderParams) (results *CreateOrderResults, err error)
	GetOrder(ctx context.Context, params *GetOrderParams) (results *GetOrderResults, err error)
}

type storeClient struct {
	apicommon.Client

	rpcInterceptorTable [2][]apicommon.RPCHandler
}

func NewStoreClient(rpcBaseURL string, options apicommon.ClientOptions) StoreClient {
	var c storeClient
	c.Init(rpcBaseURL, options)
	apicommon.FillRPCInterceptorTable(c.rpcInterceptorTable[:], options.RPCInterceptors)
	return &c
}

func (c *storeClient) CreateOrder(ctx context.Context, params *CreateOrderParams) (*CreateOrderResults, error) {
	var s struct {
		OutgoingRPC apicommon.OutgoingRPC
		Params      CreateOrderParams
		Results     CreateOrderResults
	}
	s.Params = *params
	rpcInterceptors := c.rpcInterceptorTable[Store_CreateOrder]
	s.OutgoingRPC.Init("Petstore", "Store", "CreateOrder", &s.Params, &s.Results, apicommon.HandleRPC, rpcInterceptors)
	if err := c.DoRPC(ctx, &s.OutgoingRPC, "/rpc/Petstore.Store.CreateOrder"); err != nil {
		return nil, err
	}
	return &s.Results, nil
}

func (c *storeClient) GetOrder(ctx context.Context, params *GetOrderParams) (*GetOrderResults, error) {
	var s struct {
		OutgoingRPC apicommon.OutgoingRPC
		Params      GetOrderParams
		Results     GetOrderResults
	}
	s.Params = *params
	rpcInterceptors := c.rpcInterceptorTable[Store_GetOrder]
	s.OutgoingRPC.Init("Petstore", "Store", "GetOrder", &s.Params, &s.Results, apicommon.HandleRPC, rpcInterceptors)
	if err := c.DoRPC(ctx, &s.OutgoingRPC, "/rpc/Petstore.Store.GetOrder"); err != nil {
		return nil, err
	}
	return &s.Results, nil
}

type StoreClientFuncs struct {
	CreateOrderFunc func(context.Context, *CreateOrderParams) (*CreateOrderResults, error)
	GetOrderFunc    func(context.Context, *GetOrderParams) (*GetOrderResults, error)
}

var _ StoreClient = (*StoreClientFuncs)(nil)

func (cf *StoreClientFuncs) CreateOrder(ctx context.Context, params *CreateOrderParams) (*CreateOrderResults, error) {
	if f := cf.CreateOrderFunc; f != nil {
		return f(ctx, params)
	}
	return &CreateOrderResults{}, nil
}

func (cf *StoreClientFuncs) GetOrder(ctx context.Context, params *GetOrderParams) (*GetOrderResults, error) {
	if f := cf.GetOrderFunc; f != nil {
		return f(ctx, params)
	}
	return &GetOrderResults{}, nil
}
