// Code generated by jrohc. DO NOT EDIT.

package petstoreapi

import (
	context "context"
	apicommon "github.com/go-tk/jroh/go/apicommon"
	http "net/http"
)

type StoreServer interface {
	CreateOrder(ctx context.Context, params *CreateOrderParams, results *CreateOrderResults) (err error)
	GetOrder(ctx context.Context, params *GetOrderParams, results *GetOrderResults) (err error)
}

func RegisterStoreServer(server StoreServer, serveMux *http.ServeMux, serverOptions apicommon.ServerOptions) {
	serverOptions.Sanitize()
	var rpcFiltersTable [2][]apicommon.RPCHandler
	apicommon.FillRPCFiltersTable(rpcFiltersTable[:], serverOptions.RPCFilters)
	{
		rpcFilters := rpcFiltersTable[Store_CreateOrder]
		incomingRPCFactory := func() *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      CreateOrderParams
				Results     CreateOrderResults
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return server.CreateOrder(ctx, rpc.Params().(*CreateOrderParams), rpc.Results().(*CreateOrderResults))
			}
			s.IncomingRPC.Init("Petstore", "Store", "CreateOrder", "Petstore.Store.CreateOrder", &s.Params, &s.Results, rpcHandler, rpcFilters)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(serverOptions.Middlewares, Store_CreateOrder, incomingRPCFactory, serverOptions.TraceIDGenerator)
		serveMux.Handle("/rpc/Petstore.Store.CreateOrder", handler)
	}
	{
		rpcFilters := rpcFiltersTable[Store_GetOrder]
		incomingRPCFactory := func() *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      GetOrderParams
				Results     GetOrderResults
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return server.GetOrder(ctx, rpc.Params().(*GetOrderParams), rpc.Results().(*GetOrderResults))
			}
			s.IncomingRPC.Init("Petstore", "Store", "GetOrder", "Petstore.Store.GetOrder", &s.Params, &s.Results, rpcHandler, rpcFilters)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(serverOptions.Middlewares, Store_GetOrder, incomingRPCFactory, serverOptions.TraceIDGenerator)
		serveMux.Handle("/rpc/Petstore.Store.GetOrder", handler)
	}
}

type StoreServerFuncs struct {
	CreateOrderFunc func(context.Context, *CreateOrderParams, *CreateOrderResults) error
	GetOrderFunc    func(context.Context, *GetOrderParams, *GetOrderResults) error
}

var _ StoreServer = (*StoreServerFuncs)(nil)

func (sf *StoreServerFuncs) CreateOrder(ctx context.Context, params *CreateOrderParams, results *CreateOrderResults) error {
	f := sf.CreateOrderFunc
	if f == nil {
		return apicommon.ErrNotImplemented
	}
	return f(ctx, params, results)
}

func (sf *StoreServerFuncs) GetOrder(ctx context.Context, params *GetOrderParams, results *GetOrderResults) error {
	f := sf.GetOrderFunc
	if f == nil {
		return apicommon.ErrNotImplemented
	}
	return f(ctx, params, results)
}
