// Code generated by jrohc. DO NOT EDIT.

package petstoreapi

import (
	context "context"
	fmt "fmt"
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

type UserClient interface {
	CreateUser(ctx context.Context, params *CreateUserParams) (err error)
	GetUser(ctx context.Context, params *GetUserParams) (results *GetUserResults, err error)
	GetUsers(ctx context.Context, params *GetUsersParams) (results *GetUsersResults, err error)
	UpdateUser(ctx context.Context, params *UpdateUserParams) (err error)
}

type userClient struct {
	rpcBaseURL      string
	options         apicommon.ClientOptions
	rpcFiltersTable [NumberOfUserMethods][]apicommon.OutgoingRPCHandler
}

func NewUserClient(rpcBaseURL string, options apicommon.ClientOptions) UserClient {
	var c userClient
	c.rpcBaseURL = rpcBaseURL
	c.options = options
	c.options.Sanitize()
	apicommon.FillOutgoingRPCFiltersTable(c.rpcFiltersTable[:], options.RPCFilters)
	return &c
}

func (c *userClient) CreateUser(ctx context.Context, params *CreateUserParams) error {
	var a struct {
		rpc     apicommon.OutgoingRPC
		params  CreateUserParams
		results apicommon.DummyModel
	}
	a.rpc.Namespace = "Petstore"
	a.rpc.ServiceName = "User"
	a.rpc.MethodName = "CreateUser"
	a.rpc.FullMethodName = "Petstore.User.CreateUser"
	a.rpc.MethodIndex = User_CreateUser
	a.params = *params
	a.rpc.Params = &a.params
	a.rpc.Results = &a.results
	if err := c.doRPC(ctx, &a.rpc, "/rpc/Petstore.User.CreateUser"); err != nil {
		return err
	}
	return nil
}

func (c *userClient) GetUser(ctx context.Context, params *GetUserParams) (*GetUserResults, error) {
	var a struct {
		rpc     apicommon.OutgoingRPC
		params  GetUserParams
		results GetUserResults
	}
	a.rpc.Namespace = "Petstore"
	a.rpc.ServiceName = "User"
	a.rpc.MethodName = "GetUser"
	a.rpc.FullMethodName = "Petstore.User.GetUser"
	a.rpc.MethodIndex = User_GetUser
	a.params = *params
	a.rpc.Params = &a.params
	a.rpc.Results = &a.results
	if err := c.doRPC(ctx, &a.rpc, "/rpc/Petstore.User.GetUser"); err != nil {
		return nil, err
	}
	return &a.results, nil
}

func (c *userClient) GetUsers(ctx context.Context, params *GetUsersParams) (*GetUsersResults, error) {
	var a struct {
		rpc     apicommon.OutgoingRPC
		params  GetUsersParams
		results GetUsersResults
	}
	a.rpc.Namespace = "Petstore"
	a.rpc.ServiceName = "User"
	a.rpc.MethodName = "GetUsers"
	a.rpc.FullMethodName = "Petstore.User.GetUsers"
	a.rpc.MethodIndex = User_GetUsers
	a.params = *params
	a.rpc.Params = &a.params
	a.rpc.Results = &a.results
	if err := c.doRPC(ctx, &a.rpc, "/rpc/Petstore.User.GetUsers"); err != nil {
		return nil, err
	}
	return &a.results, nil
}

func (c *userClient) UpdateUser(ctx context.Context, params *UpdateUserParams) error {
	var a struct {
		rpc     apicommon.OutgoingRPC
		params  UpdateUserParams
		results apicommon.DummyModel
	}
	a.rpc.Namespace = "Petstore"
	a.rpc.ServiceName = "User"
	a.rpc.MethodName = "UpdateUser"
	a.rpc.FullMethodName = "Petstore.User.UpdateUser"
	a.rpc.MethodIndex = User_UpdateUser
	a.params = *params
	a.rpc.Params = &a.params
	a.rpc.Results = &a.results
	if err := c.doRPC(ctx, &a.rpc, "/rpc/Petstore.User.UpdateUser"); err != nil {
		return err
	}
	return nil
}

func (c *userClient) doRPC(ctx context.Context, rpc *apicommon.OutgoingRPC, rpcPath string) error {
	if timeout := c.options.Timeout; timeout >= 1 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, timeout)
		defer cancel()
	}
	rpc.Transport = c.options.Transport
	rpc.URL = c.rpcBaseURL + rpcPath
	rpc.SetHandler(apicommon.HandleOutgoingRPC)
	rpc.SetFilters(c.rpcFiltersTable[rpc.MethodIndex])
	if err := rpc.Do(ctx); err != nil {
		return fmt.Errorf("rpc failed; fullMethodName=%q traceID=%q: %w", rpc.FullMethodName, rpc.TraceID, err)
	}
	return nil
}

type UserClientFuncs struct {
	CreateUserFunc func(context.Context, *CreateUserParams) error
	GetUserFunc    func(context.Context, *GetUserParams) (*GetUserResults, error)
	GetUsersFunc   func(context.Context, *GetUsersParams) (*GetUsersResults, error)
	UpdateUserFunc func(context.Context, *UpdateUserParams) error
}

var _ UserClient = (*UserClientFuncs)(nil)

func (cf *UserClientFuncs) CreateUser(ctx context.Context, params *CreateUserParams) error {
	if f := cf.CreateUserFunc; f != nil {
		return f(ctx, params)
	}
	return apicommon.NewNotImplementedError()
}

func (cf *UserClientFuncs) GetUser(ctx context.Context, params *GetUserParams) (*GetUserResults, error) {
	if f := cf.GetUserFunc; f != nil {
		return f(ctx, params)
	}
	return nil, apicommon.NewNotImplementedError()
}

func (cf *UserClientFuncs) GetUsers(ctx context.Context, params *GetUsersParams) (*GetUsersResults, error) {
	if f := cf.GetUsersFunc; f != nil {
		return f(ctx, params)
	}
	return nil, apicommon.NewNotImplementedError()
}

func (cf *UserClientFuncs) UpdateUser(ctx context.Context, params *UpdateUserParams) error {
	if f := cf.UpdateUserFunc; f != nil {
		return f(ctx, params)
	}
	return apicommon.NewNotImplementedError()
}
