// Code generated by jrohc. DO NOT EDIT.

package helloworldapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

const ErrorUserNotAllowed apicommon.ErrorCode = 1001

func NewUserNotAllowedError() *apicommon.Error {
	return &apicommon.Error{
		Code:    ErrorUserNotAllowed,
		Message: "user not allowed",
	}
}

var errUserNotAllowed *apicommon.Error = NewUserNotAllowedError()
var ErrUserNotAllowed error = errUserNotAllowed
