// Code generated by jrohc. DO NOT EDIT.

package helloworldapi

import (
	context "context"
	apicommon "github.com/go-tk/jroh/go/apicommon"
	http "net/http"
)

type GreeterServer interface {
	SayHello(ctx context.Context, params *SayHelloParams, results *SayHelloResults) (err error)
}

func RegisterGreeterServer(s GreeterServer, router *apicommon.Router, options apicommon.ServerOptions) {
	options.Sanitize()
	var rpcFiltersTable [NumberOfGreeterMethods][]apicommon.IncomingRPCHandler
	apicommon.FillIncomingRPCFiltersTable(rpcFiltersTable[:], options.RPCFilters)
	{
		rpcFilters := rpcFiltersTable[Greeter_SayHello]
		handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			var a struct {
				rpc     apicommon.IncomingRPC
				params  SayHelloParams
				results SayHelloResults
			}
			a.rpc.Namespace = "HelloWorld"
			a.rpc.ServiceName = "Greeter"
			a.rpc.MethodName = "SayHello"
			a.rpc.FullMethodName = "HelloWorld.Greeter.SayHello"
			a.rpc.MethodIndex = Greeter_SayHello
			a.rpc.Params = &a.params
			a.rpc.Results = &a.results
			a.rpc.SetHandler(func(ctx context.Context, rpc *apicommon.IncomingRPC) error {
				return s.SayHello(ctx, rpc.Params.(*SayHelloParams), rpc.Results.(*SayHelloResults))
			})
			a.rpc.SetFilters(rpcFilters)
			apicommon.HandleRequest(r, &a.rpc, options.TraceIDGenerator, w)
		})
		router.AddRoute("/rpc/HelloWorld.Greeter.SayHello", handler, "HelloWorld.Greeter.SayHello", rpcFilters)
	}
}

type GreeterServerFuncs struct {
	SayHelloFunc func(context.Context, *SayHelloParams, *SayHelloResults) error
}

var _ GreeterServer = (*GreeterServerFuncs)(nil)

func (sf *GreeterServerFuncs) SayHello(ctx context.Context, params *SayHelloParams, results *SayHelloResults) error {
	if f := sf.SayHelloFunc; f != nil {
		return f(ctx, params, results)
	}
	return apicommon.NewNotImplementedError()
}
