// Code generated by jrohc. DO NOT EDIT.

package helloworldapi

import (
	context "context"
	fmt "fmt"
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

type GreeterClient interface {
	SayHello(ctx context.Context, params *SayHelloParams) (results *SayHelloResults, err error)
}

type greeterClient struct {
	rpcBaseURL      string
	options         apicommon.ClientOptions
	rpcFiltersTable [NumberOfGreeterMethods][]apicommon.OutgoingRPCHandler
}

func NewGreeterClient(rpcBaseURL string, options apicommon.ClientOptions) GreeterClient {
	var c greeterClient
	c.rpcBaseURL = rpcBaseURL
	c.options = options
	c.options.Sanitize()
	apicommon.FillOutgoingRPCFiltersTable(c.rpcFiltersTable[:], options.RPCFilters)
	return &c
}

func (c *greeterClient) SayHello(ctx context.Context, params *SayHelloParams) (*SayHelloResults, error) {
	var a struct {
		rpc     apicommon.OutgoingRPC
		params  SayHelloParams
		results SayHelloResults
	}
	a.rpc.Namespace = "HelloWorld"
	a.rpc.ServiceName = "Greeter"
	a.rpc.MethodName = "SayHello"
	a.rpc.FullMethodName = "HelloWorld.Greeter.SayHello"
	a.rpc.MethodIndex = Greeter_SayHello
	a.params = *params
	a.rpc.Params = &a.params
	a.rpc.Results = &a.results
	if err := c.doRPC(ctx, &a.rpc, "/rpc/HelloWorld.Greeter.SayHello"); err != nil {
		return nil, err
	}
	return &a.results, nil
}

func (c *greeterClient) doRPC(ctx context.Context, rpc *apicommon.OutgoingRPC, rpcPath string) error {
	if timeout := c.options.Timeout; timeout >= 1 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, timeout)
		defer cancel()
	}
	rpc.Transport = c.options.Transport
	rpc.URL = c.rpcBaseURL + rpcPath
	rpc.SetHandler(apicommon.HandleOutgoingRPC)
	rpc.SetFilters(c.rpcFiltersTable[rpc.MethodIndex])
	if err := rpc.Do(ctx); err != nil {
		return fmt.Errorf("rpc failed; fullMethodName=%q traceID=%q: %w", rpc.FullMethodName, rpc.TraceID, err)
	}
	return nil
}

type GreeterClientFuncs struct {
	SayHelloFunc func(context.Context, *SayHelloParams) (*SayHelloResults, error)
}

var _ GreeterClient = (*GreeterClientFuncs)(nil)

func (cf *GreeterClientFuncs) SayHello(ctx context.Context, params *SayHelloParams) (*SayHelloResults, error) {
	if f := cf.SayHelloFunc; f != nil {
		return f(ctx, params)
	}
	return nil, apicommon.NewNotImplementedError()
}
