// Code generated by jrohc. DO NOT EDIT.

package helloworldapi

import (
	context "context"
	apicommon "github.com/go-tk/jroh/go/apicommon"
	http "net/http"
)

type GreeterServer interface {
	SayHello(ctx context.Context, params *SayHelloParams, results *SayHelloResults) (err error)
}

func RegisterGreeterServer(server GreeterServer, serveMux *http.ServeMux, serverOptions apicommon.ServerOptions) {
	serverOptions.Sanitize()
	var rpcFiltersTable [1][]apicommon.RPCHandler
	apicommon.FillRPCFiltersTable(rpcFiltersTable[:], serverOptions.RPCFilters)
	{
		rpcFilters := rpcFiltersTable[Greeter_SayHello]
		incomingRPCFactory := func() *apicommon.IncomingRPC {
			var s struct {
				IncomingRPC apicommon.IncomingRPC
				Params      SayHelloParams
				Results     SayHelloResults
			}
			rpcHandler := func(ctx context.Context, rpc *apicommon.RPC) error {
				return server.SayHello(ctx, rpc.Params().(*SayHelloParams), rpc.Results().(*SayHelloResults))
			}
			s.IncomingRPC.Init("HelloWorld", "Greeter", "SayHello", "HelloWorld.Greeter.SayHello", &s.Params, &s.Results, rpcHandler, rpcFilters)
			return &s.IncomingRPC
		}
		handler := apicommon.MakeHandler(serverOptions.Middlewares, Greeter_SayHello, incomingRPCFactory, serverOptions.TraceIDGenerator)
		serveMux.Handle("/rpc/HelloWorld.Greeter.SayHello", handler)
	}
}

type GreeterServerFuncs struct {
	SayHelloFunc func(context.Context, *SayHelloParams, *SayHelloResults) error
}

var _ GreeterServer = (*GreeterServerFuncs)(nil)

func (sf *GreeterServerFuncs) SayHello(ctx context.Context, params *SayHelloParams, results *SayHelloResults) error {
	f := sf.SayHelloFunc
	if f == nil {
		return apicommon.ErrNotImplemented
	}
	return f(ctx, params, results)
}
