// Code generated by jrohc. DO NOT EDIT.

package helloworldapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

const (
	Greeter_SayHello apicommon.MethodIndex = 0
)

const NumberOfGreeterMethods = 1
