// Code generated by jrohc. DO NOT EDIT.

package helloworldapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

type SayHelloParams struct {
	Name string `json:"name"`
}

var _ apicommon.Validator = (*SayHelloParams)(nil)

func (m *SayHelloParams) Validate(validationContext *apicommon.ValidationContext) bool {
	{
		validationContext.Enter("name")
		if len(m.Name) < 1 {
			validationContext.SetErrorDetails("length < 1")
			return false
		}
		validationContext.Leave()
	}
	return true
}

type SayHelloResults struct {
	Message string `json:"message"`
}

var _ apicommon.Validator = (*SayHelloResults)(nil)

func (m *SayHelloResults) Validate(validationContext *apicommon.ValidationContext) bool {
	{
		validationContext.Enter("message")
		if len(m.Message) < 1 {
			validationContext.SetErrorDetails("length < 1")
			return false
		}
		validationContext.Leave()
	}
	return true
}
