// Code generated by jrohc. DO NOT EDIT.

package fooapi

import (
	apicommon "github.com/go-tk/jroh/go/apicommon"
)

const (
	Test_DoSomething  apicommon.MethodIndex = 0
	Test_DoSomething2 apicommon.MethodIndex = 1
	Test_DoSomething3 apicommon.MethodIndex = 2
)

const NumberOfTestMethods = 3
