name: ci
defaults:
  run:
    shell: bash
on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
    branches:
    - main
jobs:
  test:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - uses: actions/checkout@v2
    - run: DEBUG=1 make envrc
    - run: source .envrc && DEBUG=1 make
    - run: git diff --exit-code
  build_and_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - run: >-
        curl
        -H 'Accept: application/vnd.github+json'
        -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
        -SsLf '${{ github.api_url }}/repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs?check_name=test'
        | jq --raw-output '.check_runs[-1].conclusion'
        | grep --line-regexp --fixed-strings success
    - run: |-
        echo "tag=${GITHUB_REF#refs/tags/}" >>"${GITHUB_ENV}"
        echo "image=ghcr.io/go-tk/jrohc:${GITHUB_REF#refs/tags/}" >>"${GITHUB_ENV}"
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker build --tag='${{ env.image }}' . && docker push '${{ env.image }}'
    - run: >-
        curl
        -H 'Accept: application/vnd.github+json'
        -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
        -d '{"ref":"refs/tags/go/${{ env.tag }}", "sha":"${{ github.sha }}"}'
        -SsLf '${{ github.api_url }}/repos/${{ github.repository }}/git/refs'
