defaults:
  run:
    shell: bash
on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - if: startsWith(github.ref, 'refs/tags/')
      run: 'git fetch origin "+${GITHUB_REF}:${GITHUB_REF}"'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: DEBUG=1 make envrc
    - run: source .envrc && DEBUG=1 make
    - run: git diff --exit-code
    - run: source .envrc && DEBUG=1 PUSHIMAGE=1 make image
