name: main
defaults:
  run:
    shell: bash
on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - uses: actions/checkout@v2
    - run: DEBUG=1 make envrc
    - run: source .envrc && DEBUG=1 make
    - run: git diff --exit-code
  build:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - run: echo "tag=${GITHUB_REF#refs/tags/}" >>"${GITHUB_ENV}"
    - run: echo 'image=ghcr.io/go-tk/jrohc:${{ env.tag }}' >>"${GITHUB_ENV}"
    - uses: actions/checkout@v2
    - run: docker build --tag='${{ env.image }}' .
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker push '${{ env.image }}'
    - uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/go/${{ env.tag }}",
            sha: context.sha
          })
